export const spaData = [
  {
    url: 'https://iamrealmarsel.github.io/151240-what-to-watch-5/public',
    urlGithub: 'https://github.com/iamrealmarsel/151240-what-to-watch-5',
    srcPreview: 'spa/what-to-watch.jpg',
    tags: ['spa', 'react'],
    year: '2021 April',
  },
  {
    url: 'https://iamrealmarsel.github.io/151240-cinemaddict-12/public',
    urlGithub: 'https://github.com/iamrealmarsel/151240-cinemaddict-12',
    srcPreview: 'spa/cinemaddict.jpg',
    tags: ['spa'],
    year: '2020 October',
  },
  {
    url: 'https://iamrealmarsel.github.io/projects/spa/react-sneakers/build/',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/spa/react-sneakers',
    pathDescription: '/react-sneakers',
    srcPreview: 'spa/react-sneakers.jpg',
    tags: ['spa', 'react'],
    year: '2021 July',
  },
  {
    url: 'https://react-pizza-demo.herokuapp.com/',
    urlGithub: 'https://github.com/iamrealmarsel/react-pizza',
    srcPreview: 'spa/react-pizza.jpg',
    tags: ['spa', 'react'],
    year: '2021 July',
  },
  {
    url: 'https://iamrealmarsel.github.io/css-mem-slider',
    urlGithub: 'https://github.com/iamrealmarsel/css-mem-slider',
    pathDescription: '/css-mem-slider',
    srcPreview: 'css-mem-slider.jpg',
    tags: ['one page'],
    year: '2022 May',
  },
  {
    url: 'https://iamrealmarsel.github.io/disney-toy-store',
    urlGithub: 'https://github.com/iamrealmarsel/disney-toy-store',
    pathDescription: '/disney-toy-store',
    srcPreview: 'disney-toy-store.jpg',
    tags: ['spa'],
    year: '2022 July',
  },
  {
    url: 'https://iamrealmarsel.github.io/virtual-keyboard',
    urlGithub: 'https://github.com/iamrealmarsel/virtual-keyboard',
    pathDescription: '/virtual-keyboard',
    srcPreview: 'virtual-keyboard.jpg',
    tags: ['spa'],
    year: '2022 May',
  },
  {
    url: 'https://iamrealmarsel.github.io/shelter-cozy-house',
    urlGithub: 'https://github.com/iamrealmarsel/shelter-cozy-house',
    pathDescription: '/shelter-cozy-house',
    srcPreview: 'shelter-cozy-house.jpg',
    tags: ['multi page'],
    year: '2022 April',
  },
  {
    url: 'https://iamrealmarsel.github.io/async-race',
    urlGithub: 'https://github.com/iamrealmarsel/async-race',
    pathDescription: '/async-race',
    srcPreview: 'async-race.jpg',
    tags: ['spa'],
    year: '2022 August',
  },
  {
    url: 'https://rs-lang-mars.netlify.app',
    urlGithub: 'https://github.com/iamrealmarsel/rs-lang',
    pathDescription: '/rs-lang',
    srcPreview: 'rs-lang.jpg',
    tags: ['spa', 'react'],
    year: '2022 September',
  },
  // {
  //   url: 'https://iamrealmarsel.github.io/projects/one-page/express-test',
  //   urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/one-page/express-test',
  //   srcPreview: 'one-page/express-test.jpg',
  //   // tags: ['spa', 'react'],
  //   tags: ['one page'],
  //   year: '2019 April',
  // },
];
