export default [
  {
    id: 7,
    url: 'https://iamrealmarsel.github.io/projects/websites/fortfamily-startup',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/fortfamily-startup',
    srcDescription: 'static.md',
    srcPreview: 'websites/fortfamily-startup.jpg',
    tags: ['static'],
    year: '2019 October',
  },
  {
    id: 8,
    url: 'https://iamrealmarsel.github.io/projects/websites/fortfamily-investments',
    urlGithub:
      'https://github.com/iamrealmarsel/projects/tree/main/websites/fortfamily-investments',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/fortfamily-investments.jpg',
    tags: ['static', 'landing page'],
    year: '2019 July',
  },
  {
    id: 9,
    url: 'https://iamrealmarsel.github.io/projects/websites/amarkets/no-deposit-iphonesx',
    urlGithub:
      'https://github.com/iamrealmarsel/projects/tree/main/websites/amarkets/no-deposit-iphonesx',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/amarkets-no-deposit-iphonesx.jpg',
    tags: ['static', 'landing page'],
    year: '2018 August',
  },
  {
    id: 10,
    url: 'https://iamrealmarsel.github.io/projects/websites/amarkets/bitcoin/dist',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/amarkets/bitcoin',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/amarkets-bitcoin.jpg',
    tags: ['static', 'landing page'],
    year: '2018 July',
  },
  {
    id: 11,
    url: 'https://iamrealmarsel.github.io/projects/websites/keksobooking',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/keksobooking',
    srcDescription: 'keksobooking.md',
    srcPreview: 'websites/keksobooking.jpg',
    tags: ['static'],
    year: '2018 May',
  },
  {
    id: 12,
    url: 'https://iamrealmarsel.github.io/projects/websites/amarkets/africa/dist',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/amarkets/africa',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/amarkets-africa.jpg',
    tags: ['static', 'landing page'],
    year: '2018 April',
  },
  {
    id: 13,
    url: 'https://iamrealmarsel.github.io/projects/websites/amarkets/alfaforex/dist',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/amarkets/alfaforex',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/amarkets-alfaforex.jpg',
    tags: ['static', 'landing page'],
    year: '2018 March',
  },
  {
    id: 14,
    url: 'https://iamrealmarsel.github.io/projects/websites/amarkets/apilot/dist',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/amarkets/apilot',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/amarkets-apilot.jpg',
    tags: ['static', 'landing page'],
    year: '2018 March',
  },
  {
    id: 15,
    url: 'https://iamrealmarsel.github.io/projects/websites/amarkets/casino/dist',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/amarkets/casino',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/amarkets-casino.jpg',
    tags: ['static', 'landing page'],
    year: '2018 March',
  },
  {
    id: 16,
    url: 'https://iamrealmarsel.github.io/projects/websites/amarkets/indonesia/dist',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/amarkets/indonesia',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/amarkets-indonesia.jpg',
    tags: ['static', 'landing page'],
    year: '2018 February',
  },
  {
    id: 17,
    url: 'https://iamrealmarsel.github.io/projects/websites/amarkets/webinar-korzhenevsky/app',
    urlGithub:
      'https://github.com/iamrealmarsel/projects/tree/main/websites/amarkets/webinar-korzhenevsky',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/amarkets-webinar-korzhenevsky.jpg',
    tags: ['static', 'landing page'],
    year: '2018 August',
  },
  {
    id: 18,
    url: 'https://iamrealmarsel.github.io/projects/websites/fit-n-go/dist',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/fit-n-go',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/fit-n-go.jpg',
    tags: ['static', 'landing page'],
    year: '2018 January',
  },
  {
    id: 19,
    url: 'https://iamrealmarsel.github.io/projects/websites/jet-skills',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/jet-skills',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/jet-skills.jpg',
    tags: ['static', 'landing page'],
    year: '2017 November',
  },
  {
    id: 20,
    url: 'https://iamrealmarsel.github.io/projects/websites/yurius',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/yurius',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/yurius.jpg',
    tags: ['static', 'landing page'],
    year: '2017 November',
  },
  {
    id: 21,
    url: 'https://iamrealmarsel.github.io/projects/websites/amarkets/10-years',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/amarkets/10-years',
    srcDescription: 'amarkets-10-years.md',
    srcPreview: 'websites/amarkets-10-years.jpg',
    tags: ['static', 'landing page', 'animation'],
    year: '2017 October',
  },
  {
    id: 22,
    url: 'https://iamrealmarsel.github.io/projects/websites/mark-invest',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/mark-invest',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/mark-invest.jpg',
    tags: ['static', 'landing page'],
    year: '2017 Sep',
  },
  {
    id: 23,
    url: 'https://iamrealmarsel.github.io/projects/websites/atol-service',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/atol-service',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/atol-service.jpg',
    tags: ['static', 'landing page'],
    year: '2017 July',
  },
  {
    id: 24,
    url: 'https://iamrealmarsel.github.io/projects/websites/atol-online',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/atol-online',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/atol-online.jpg',
    tags: ['static', 'landing page'],
    year: '2017 June',
  },
  {
    id: 25,
    url: 'https://iamrealmarsel.github.io/projects/websites/eat-to-be-fit',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/eat-to-be-fit',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/eat-to-be-fit.jpg',
    tags: ['static', 'landing page'],
    year: '2017 May',
  },
  {
    id: 26,
    url: 'https://iamrealmarsel.github.io/projects/websites/yorso',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/yorso',
    srcDescription: 'landing-page.md',
    srcPreview: 'websites/yorso.jpg',
    tags: ['static', 'landing page'],
    year: '2017 May',
  },
  {
    id: 27,
    url: 'https://iamrealmarsel.github.io/projects/websites/programmatic-lab/dist',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/programmatic-lab',
    srcDescription: 'programmatic-lab.md',
    srcPreview: 'websites/programmatic-lab.jpg',
    tags: ['static', 'animation'],
    year: '2018 May',
  },
  {
    id: 28,
    url: 'https://iamrealmarsel.github.io/projects/websites/swimming-academy/dist',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/swimming-academy',
    srcDescription: 'static-multi-page.md',
    srcPreview: 'websites/swimming-academy.jpg',
    tags: ['static'],
    year: '2018 May',
  },
  {
    id: 29,
    url: 'https://iamrealmarsel.github.io/projects/websites/neva-energy/dist',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/neva-energy',
    srcDescription: 'static-multi-page.md',
    srcPreview: 'websites/neva-energy.jpg',
    tags: ['static'],
    year: '2018 April',
  },
  {
    id: 30,
    url: 'https://iamrealmarsel.github.io/projects/websites/himtex',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/himtex',
    srcDescription: 'static-multi-page.md',
    srcPreview: 'websites/himtex.jpg',
    tags: ['static'],
    year: '2017 November',
  },
  {
    id: 31,
    url: 'https://iamrealmarsel.github.io/projects/websites/euro-pharma',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/euro-pharma',
    srcDescription: 'static-multi-page.md',
    srcPreview: 'websites/euro-pharma.jpg',
    tags: ['static'],
    year: '2017 October',
  },
  {
    id: 32,
    url: 'https://iamrealmarsel.github.io/projects/websites/service-for-all',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/service-for-all',
    srcDescription: 'static-multi-page.md',
    srcPreview: 'websites/service-for-all.jpg',
    tags: ['static', 'my design'],
    year: '2017 June',
  },
  {
    id: 33,
    url: 'https://iamrealmarsel.github.io/projects/websites/kommunal-service',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/kommunal-service',
    srcDescription: 'static-multi-page.md',
    srcPreview: 'websites/kommunal-service.jpg',
    tags: ['static'],
    year: '2017 May',
  },
  {
    id: 34,
    url: 'https://iamrealmarsel.github.io/projects/websites/kd',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/kd',
    srcDescription: 'static-multi-page.md',
    srcPreview: 'websites/kd.jpg',
    tags: ['static'],
    year: '2017 March',
  },
  {
    id: 35,
    url: 'https://iamrealmarsel.github.io/151240-what-to-watch-5/public',
    urlGithub: 'https://github.com/iamrealmarsel/151240-what-to-watch-5',
    srcDescription: 'what-to-watch.md',
    srcPreview: 'websites/what-to-watch.jpg',
    tags: ['spa', 'react'],
    year: '2021 April',
  },
  {
    id: 36,
    url: 'https://iamrealmarsel.github.io/151240-cinemaddict-12/public',
    urlGithub: 'https://github.com/iamrealmarsel/151240-cinemaddict-12',
    srcDescription: 'cinemaddict.md',
    srcPreview: 'websites/cinemaddict.jpg',
    tags: ['spa'],
    year: '2020 October',
  },
  {
    id: 37,
    url: 'https://iamrealmarsel.github.io/projects/websites/react-sneakers/build/',
    urlGithub: 'https://github.com/iamrealmarsel/projects/tree/main/websites/react-sneakers',
    srcDescription: 'react-sneakers.md',
    srcPreview: 'websites/react-sneakers.jpg',
    tags: ['spa', 'react'],
    year: '2021 July',
  },
  {
    id: 38,
    url: 'https://react-pizza-demo.herokuapp.com/',
    urlGithub: 'https://github.com/iamrealmarsel/react-pizza',
    srcDescription: 'react-pizza.md',
    srcPreview: 'websites/react-pizza.jpg',
    tags: ['spa', 'react'],
    year: '2021 July',
  },
  {
    id: 39,
    url: 'https://iamrealmarsel.github.io/css-mem-slider',
    urlGithub: 'https://github.com/iamrealmarsel/css-mem-slider',
    srcDescription: 'css-mem-slider.md',
    srcPreview: 'websites/css-mem-slider.jpg',
    tags: ['static', 'my design'],
    year: '2022 May',
  },
  {
    id: 40,
    url: 'https://iamrealmarsel.github.io/disney-toy-store',
    urlGithub: 'https://github.com/iamrealmarsel/disney-toy-store',
    srcDescription: 'disney-toy-store.md',
    srcPreview: 'websites/disney-toy-store.jpg',
    tags: ['spa', 'typescript', 'my design'],
    year: '2022 July',
  },
  {
    id: 41,
    url: 'https://iamrealmarsel.github.io/virtual-keyboard',
    urlGithub: 'https://github.com/iamrealmarsel/virtual-keyboard',
    srcDescription: 'virtual-keyboard.md',
    srcPreview: 'websites/virtual-keyboard.jpg',
    tags: ['spa', 'my design'],
    year: '2022 May',
  },
  {
    id: 42,
    url: 'https://iamrealmarsel.github.io/shelter-cozy-house',
    urlGithub: 'https://github.com/iamrealmarsel/shelter-cozy-house',
    srcDescription: 'shelter-cozy-house.md',
    srcPreview: 'websites/shelter-cozy-house.jpg',
    tags: ['static'],
    year: '2022 April',
  },
  {
    id: 43,
    url: 'https://iamrealmarsel.github.io/async-race',
    urlGithub: 'https://github.com/iamrealmarsel/async-race',
    srcDescription: 'async-race.md',
    srcPreview: 'websites/async-race.jpg',
    tags: ['spa', 'typescript', 'my design'],
    year: '2022 August',
  },
  {
    id: 44,
    url: 'https://rs-lang-mars.netlify.app',
    urlGithub: 'https://github.com/iamrealmarsel/rs-lang',
    srcDescription: 'rs-lang.md',
    srcPreview: 'websites/rs-lang.jpg',
    tags: ['spa', 'react', 'typescript'],
    year: '2022 September',
  },
];
